/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class martyr_struct_Ontology */

#ifndef _Included_martyr_struct_Ontology
#define _Included_martyr_struct_Ontology
#ifdef __cplusplus
extern "C" {
#endif
#undef martyr_struct_Ontology_CLASS
#define martyr_struct_Ontology_CLASS 0L
#undef martyr_struct_Ontology_DATAPROP
#define martyr_struct_Ontology_DATAPROP 1L
#undef martyr_struct_Ontology_OBJPROP
#define martyr_struct_Ontology_OBJPROP 2L
#undef martyr_struct_Ontology_EVENT
#define martyr_struct_Ontology_EVENT 4L
#undef martyr_struct_Ontology_ACTPROP
#define martyr_struct_Ontology_ACTPROP 3L
#undef martyr_struct_Ontology_NOTMAINTAG
#define martyr_struct_Ontology_NOTMAINTAG 5L
/*
 * Class:     martyr_struct_Ontology
 * Method:    mioatize_class
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_martyr_struct_Ontology_mioatize_1class
  (JNIEnv *, jobject, jstring);

/*
 * Class:     martyr_struct_Ontology
 * Method:    mioatize_subclass
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_martyr_struct_Ontology_mioatize_1subclass
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     martyr_struct_Ontology
 * Method:    mioatize_subevent
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_martyr_struct_Ontology_mioatize_1subevent
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     martyr_struct_Ontology
 * Method:    mioatize_property
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_martyr_struct_Ontology_mioatize_1property
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     martyr_struct_Ontology
 * Method:    mioatize_activeproperty
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_martyr_struct_Ontology_mioatize_1activeproperty
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     martyr_struct_Ontology
 * Method:    mioatize_getInsValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_martyr_struct_Ontology_mioatize_1getInsValue
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     martyr_struct_Ontology
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_martyr_struct_Ontology_test
  (JNIEnv *, jobject);

/*
 * Class:     martyr_struct_Ontology
 * Method:    mioatize_create
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_martyr_struct_Ontology_mioatize_1create
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     martyr_struct_Ontology
 * Method:    mioatize_values
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_martyr_struct_Ontology_mioatize_1values
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     martyr_struct_Ontology
 * Method:    mioatize_objective
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_martyr_struct_Ontology_mioatize_1objective
  (JNIEnv *, jobject, jstring);

/*
 * Class:     martyr_struct_Ontology
 * Method:    mioatize_execution
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_martyr_struct_Ontology_mioatize_1execution
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     martyr_struct_Ontology
 * Method:    cleanMIOA
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_martyr_struct_Ontology_cleanMIOA
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
